services:
  - type: web
    name: bland-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BLAND_API_KEY
        sync: false
      - key: BASE_URL
        sync: false
